/**
 * !!! THIS FILE IS AUTOMATICALLY GENERATED, PLEASE DO NOT EDIT THIS FILE MANUALLY !!!
 *
 * Generated by: @PostgreSQL-Typed/CLI
 * Checksum: xJ47vn40qV6/f6v1URJuTQXWUda+xBGCpJjXbJbWTdPDcpON/Kuz0wqTUzLimZJqBnEO49sEGftVatPESWL1tg==
 */

/* eslint-disable */
// tslint:disable
/* deepscan-disable */

import {CharacterVarying, PGTPParser} from "@postgresql-typed/parsers";

import { Users, Users_Data } from './users';

interface Addresses {
  /**
   * @kind character varying(30)
   */
  city: CharacterVarying<30>
  /**
   * @kind character varying(30)
   */
  state: CharacterVarying<30>
  /**
   * @kind character varying(30)
   */
  street: CharacterVarying<30>
  /**
   * @kind PrimaryKey
   * 
   * @kind integer
   */
  user_id: Users['id']
}
export type {Addresses}

const Addresses_Data = {
  /**
   * @kind character varying(30)
   */
  city: PGTPParser(CharacterVarying.setN(30)),
  /**
   * @kind character varying(30)
   */
  state: PGTPParser(CharacterVarying.setN(30)),
  /**
   * @kind character varying(30)
   */
  street: PGTPParser(CharacterVarying.setN(30)),
  /**
   * @kind PrimaryKey
   * 
   * @kind integer
   */
  user_id: PGTPParser(Users_Data['id']),
};
export {Addresses_Data}

interface Addresses_InsertParameters {
  /**
   * @kind character varying(30)
   */
  city: CharacterVarying<30>
  /**
   * @kind character varying(30)
   */
  state: CharacterVarying<30>
  /**
   * @kind character varying(30)
   */
  street: CharacterVarying<30>
  /**
   * @kind PrimaryKey
   * 
   * @kind integer
   */
  user_id: Users['id']
}
export type {Addresses_InsertParameters}

const Addresses_InsertParameters_Data = {
  /**
   * @kind character varying(30)
   */
  city: PGTPParser(CharacterVarying.setN(30)),
  /**
   * @kind character varying(30)
   */
  state: PGTPParser(CharacterVarying.setN(30)),
  /**
   * @kind character varying(30)
   */
  street: PGTPParser(CharacterVarying.setN(30)),
  /**
   * @kind PrimaryKey
   * 
   * @kind integer
   */
  user_id: PGTPParser(Users_Data['id']),
};
export {Addresses_InsertParameters_Data}

const Addresses_PrimaryKey: "user_id" = "user_id"
export {Addresses_PrimaryKey}
