/**
 * !!! THIS FILE IS AUTOMATICALLY GENERATED, PLEASE DO NOT EDIT THIS FILE MANUALLY !!!
 *
 * Generated by: @PostgreSQL-Typed/CLI
 * Checksum: CDElJza6gtuk8O568B/gRsEPdE3pte2FPCerlpwNj4nC7oiXGw468M5Vq9aBzdo6giy5GoNF4WIjmgswoRulWg==
 */

/* eslint-disable */
// tslint:disable
/* deepscan-disable */

import {CharacterVarying, OID, PGTPParser} from "@postgresql-typed/parsers";

interface Aircraft {
  /**
   * @kind character varying(90)
   */
  name: CharacterVarying<90> | null
  /**
   * link:public.users.id
   * 
   * @kind PrimaryKey
   * 
   * @kind oid
   */
  oid: OID
}
export type {Aircraft}

const Aircraft_Data = {
  /**
   * @kind character varying(90)
   */
  name: PGTPParser(CharacterVarying.setN(90)).nullable(),
  /**
   * link:public.users.id
   * 
   * @kind PrimaryKey
   * 
   * @kind oid
   */
  oid: PGTPParser(OID),
};
export {Aircraft_Data}

interface Aircraft_InsertParameters {
  /**
   * @kind character varying(90)
   */
  name?: CharacterVarying<90> | null
  /**
   * link:public.users.id
   * 
   * @kind PrimaryKey
   * 
   * @kind oid
   */
  oid: OID
}
export type {Aircraft_InsertParameters}

const Aircraft_InsertParameters_Data = {
  /**
   * @kind character varying(90)
   */
  name: PGTPParser(CharacterVarying.setN(90)).nullable().optional(),
  /**
   * link:public.users.id
   * 
   * @kind PrimaryKey
   * 
   * @kind oid
   */
  oid: PGTPParser(OID),
};
export {Aircraft_InsertParameters_Data}

const Aircraft_PrimaryKey: "oid" = "oid"
export {Aircraft_PrimaryKey}
