/**
 * !!! THIS FILE IS AUTOMATICALLY GENERATED, PLEASE DO NOT EDIT THIS FILE MANUALLY !!!
 *
 * Generated by: @PostgreSQL-Typed/CLI
 * Checksum: /eCGb3djQwYdlSUkauyGUlHmGuRViCTuO9Peglk0lfEr+j72SkWAXB/V4jiVs9R5hseA6hXfgN1jfGI1dAil1A==
 */

/* eslint-disable */
// tslint:disable
/* deepscan-disable */

import {Int4, Text, PGTPParser} from "@postgresql-typed/parsers";

interface Article {
  /**
   * @kind PrimaryKey
   * 
   * @kind integer
   * 
   * @default nextval('article_id_seq'::regclass)
   */
  id: Int4
  /**
   * @kind text
   */
  title: Text | null
}
export type {Article}

const Article_Data = {
  /**
   * @kind PrimaryKey
   * 
   * @kind integer
   * 
   * @default nextval('article_id_seq'::regclass)
   */
  id: PGTPParser(Int4),
  /**
   * @kind text
   */
  title: PGTPParser(Text).nullable(),
};
export {Article_Data}

interface Article_InsertParameters {
  /**
   * @kind PrimaryKey
   * 
   * @kind integer
   * 
   * @default nextval('article_id_seq'::regclass)
   */
  id?: Int4
  /**
   * @kind text
   */
  title?: Text | null
}
export type {Article_InsertParameters}

const Article_InsertParameters_Data = {
  /**
   * @kind PrimaryKey
   * 
   * @kind integer
   * 
   * @default nextval('article_id_seq'::regclass)
   */
  id: PGTPParser(Int4).optional(),
  /**
   * @kind text
   */
  title: PGTPParser(Text).nullable().optional(),
};
export {Article_InsertParameters_Data}

const Article_PrimaryKey: "id" = "id"
export {Article_PrimaryKey}
