/**
 * !!! THIS FILE IS AUTOMATICALLY GENERATED, PLEASE DO NOT EDIT THIS FILE MANUALLY !!!
 *
 * Generated by: @PostgreSQL-Typed/CLI
 * Checksum: AYGV1fEiIQoZbs2oT4SsLLLhgCabTqu7JTAodVpLpWVUTbPMk4zds1ZnrhMY6xbPUw0dcI9XI1ngDNlz8iOCOA==
 */

/* eslint-disable */
// tslint:disable
/* deepscan-disable */

import {PGTPParser} from "@postgresql-typed/parsers";

import { Article, Article_Data } from './article';
import { Tag, Tag_Data } from './tag';

interface ArticleTag {
  /**
   * @kind PrimaryKey
   * 
   * @kind integer
   */
  article_id: Article['id']
  /**
   * @kind PrimaryKey
   * 
   * @kind integer
   */
  tag_id: Tag['id']
}
export type {ArticleTag}

const ArticleTag_Data = {
  /**
   * @kind PrimaryKey
   * 
   * @kind integer
   */
  article_id: PGTPParser(Article_Data['id']),
  /**
   * @kind PrimaryKey
   * 
   * @kind integer
   */
  tag_id: PGTPParser(Tag_Data['id']),
};
export {ArticleTag_Data}

interface ArticleTag_InsertParameters {
  /**
   * @kind PrimaryKey
   * 
   * @kind integer
   */
  article_id: Article['id']
  /**
   * @kind PrimaryKey
   * 
   * @kind integer
   */
  tag_id: Tag['id']
}
export type {ArticleTag_InsertParameters}

const ArticleTag_InsertParameters_Data = {
  /**
   * @kind PrimaryKey
   * 
   * @kind integer
   */
  article_id: PGTPParser(Article_Data['id']),
  /**
   * @kind PrimaryKey
   * 
   * @kind integer
   */
  tag_id: PGTPParser(Tag_Data['id']),
};
export {ArticleTag_InsertParameters_Data}

const ArticleTag_PrimaryKey: "article_id" = "article_id"
export {ArticleTag_PrimaryKey}
