/**
 * !!! THIS FILE IS AUTOMATICALLY GENERATED, PLEASE DO NOT EDIT THIS FILE MANUALLY !!!
 *
 * Generated by: @PostgreSQL-Typed/CLI
 * Checksum: mCSON7GyVM4PDBZFapBxENLGZ+anSR//cMj6/HrKQzpqMSCQk4QxZU19OSCGogzKQJS9WiXvWrJaiOdPF4wE6g==
 */

/* eslint-disable */
// tslint:disable
/* deepscan-disable */

import {Text, PGTPParser} from "@postgresql-typed/parsers";

interface Courses {
  /**
   * @kind PrimaryKey
   * 
   * @kind text
   */
  course_id: Text
  /**
   * @kind text
   */
  course_name: Text
}
export type {Courses}

const Courses_Data = {
  /**
   * @kind PrimaryKey
   * 
   * @kind text
   */
  course_id: PGTPParser(Text),
  /**
   * @kind text
   */
  course_name: PGTPParser(Text),
};
export {Courses_Data}

interface Courses_InsertParameters {
  /**
   * @kind PrimaryKey
   * 
   * @kind text
   */
  course_id: Text
  /**
   * @kind text
   */
  course_name: Text
}
export type {Courses_InsertParameters}

const Courses_InsertParameters_Data = {
  /**
   * @kind PrimaryKey
   * 
   * @kind text
   */
  course_id: PGTPParser(Text),
  /**
   * @kind text
   */
  course_name: PGTPParser(Text),
};
export {Courses_InsertParameters_Data}

const Courses_PrimaryKey: "course_id" = "course_id"
export {Courses_PrimaryKey}
