/**
 * !!! THIS FILE IS AUTOMATICALLY GENERATED, PLEASE DO NOT EDIT THIS FILE MANUALLY !!!
 *
 * Generated by: @PostgreSQL-Typed/CLI
 * Checksum: fpBb3db2NI4aCCkz8y6fcyH5XL7sqKC4yThT4eBwU3sxhwhlHoRxqQsm/6iynUcdfLX8JY0PXq16PTqUvfxirA==
 */

/* eslint-disable */
// tslint:disable
/* deepscan-disable */

import {Text, Float8, PGTPParser} from "@postgresql-typed/parsers";

interface Grades {
  /**
   * @kind PrimaryKey
   * 
   * @kind text
   */
  grade: Text
  /**
   * @kind double precision
   */
  points: Float8
}
export type {Grades}

const Grades_Data = {
  /**
   * @kind PrimaryKey
   * 
   * @kind text
   */
  grade: PGTPParser(Text),
  /**
   * @kind double precision
   */
  points: PGTPParser(Float8),
};
export {Grades_Data}

interface Grades_InsertParameters {
  /**
   * @kind PrimaryKey
   * 
   * @kind text
   */
  grade: Text
  /**
   * @kind double precision
   */
  points: Float8
}
export type {Grades_InsertParameters}

const Grades_InsertParameters_Data = {
  /**
   * @kind PrimaryKey
   * 
   * @kind text
   */
  grade: PGTPParser(Text),
  /**
   * @kind double precision
   */
  points: PGTPParser(Float8),
};
export {Grades_InsertParameters_Data}

const Grades_PrimaryKey: "grade" = "grade"
export {Grades_PrimaryKey}
