/**
 * !!! THIS FILE IS AUTOMATICALLY GENERATED, PLEASE DO NOT EDIT THIS FILE MANUALLY !!!
 *
 * Generated by: @PostgreSQL-Typed/CLI
 * Checksum: uGedT0ccy2ffZxoLNbXaaPUWMonlIDE9yHE9rKzPa3NT2/sinelqCptsVa5x3L0/TJBVcgDCorsY+s7adF8Paw==
 */

/* eslint-disable */
// tslint:disable
/* deepscan-disable */

import {TimestampTZMultiRange, TimestampMultiRange, Int2, CharacterVarying, PGTPParser} from "@postgresql-typed/parsers";

interface Newtable {
  /**
   * @kind tstzmultirange[]
   */
  column1: TimestampTZMultiRange[] | null
  /**
   * @kind numeric(3,5)
   */
  column10: number | null
  /**
   * @kind numeric(2,-1)
   */
  column11: number | null
  /**
   * [extra1]:true
   * 
   * @kind numeric(2,-10)
   */
  column12: number | null
  /**
   * [extra2]:1
   * 
   * @kind numeric(2,1000)
   */
  column13: number | null
  /**
   * [extra3]:{key: "value"}
   * 
   * @kind numeric(2,-1000)
   */
  column14: number | null
  /**
   * @kind tsmultirange[]
   */
  column2: TimestampMultiRange[] | null
  /**
   * @kind smallint
   * 
   * @default nextval('newtable_column3_seq'::regclass)
   */
  column3: Int2 | null
  /**
   * @kind smallint
   */
  column4: Int2 | null
  /**
   * @kind character varying(45)
   */
  column5: CharacterVarying<45> | null
  /**
   * @kind numeric
   */
  column6: number | null
  /**
   * @kind numeric(7,3)
   */
  column7: number | null
  /**
   * @kind numeric(6,0)
   */
  column8: number | null
  /**
   * @kind numeric(2,-3)
   */
  column9: number | null
}
export type {Newtable}

const Newtable_Data = {
  /**
   * @kind tstzmultirange[]
   */
  column1: PGTPParser(TimestampTZMultiRange, true).nullable(),
  /**
   * @kind numeric(3,5)
   */
  column10: PGTPParser('unknown').nullable(),
  /**
   * @kind numeric(2,-1)
   */
  column11: PGTPParser('unknown').nullable(),
  /**
   * [extra1]:true
   * 
   * @kind numeric(2,-10)
   */
  column12: PGTPParser('unknown').nullable(),
  /**
   * [extra2]:1
   * 
   * @kind numeric(2,1000)
   */
  column13: PGTPParser('unknown').nullable(),
  /**
   * [extra3]:{key: "value"}
   * 
   * @kind numeric(2,-1000)
   */
  column14: PGTPParser('unknown').nullable(),
  /**
   * @kind tsmultirange[]
   */
  column2: PGTPParser(TimestampMultiRange, true).nullable(),
  /**
   * @kind smallint
   * 
   * @default nextval('newtable_column3_seq'::regclass)
   */
  column3: PGTPParser(Int2).nullable(),
  /**
   * @kind smallint
   */
  column4: PGTPParser(Int2).nullable(),
  /**
   * @kind character varying(45)
   */
  column5: PGTPParser(CharacterVarying.setN(45)).nullable(),
  /**
   * @kind numeric
   */
  column6: PGTPParser('unknown').nullable(),
  /**
   * @kind numeric(7,3)
   */
  column7: PGTPParser('unknown').nullable(),
  /**
   * @kind numeric(6,0)
   */
  column8: PGTPParser('unknown').nullable(),
  /**
   * @kind numeric(2,-3)
   */
  column9: PGTPParser('unknown').nullable(),
};
export {Newtable_Data}

interface Newtable_InsertParameters {
  /**
   * @kind tstzmultirange[]
   */
  column1?: TimestampTZMultiRange[] | null
  /**
   * @kind numeric(3,5)
   */
  column10?: number | null
  /**
   * @kind numeric(2,-1)
   */
  column11?: number | null
  /**
   * [extra1]:true
   * 
   * @kind numeric(2,-10)
   */
  column12?: number | null
  /**
   * [extra2]:1
   * 
   * @kind numeric(2,1000)
   */
  column13?: number | null
  /**
   * [extra3]:{key: "value"}
   * 
   * @kind numeric(2,-1000)
   */
  column14?: number | null
  /**
   * @kind tsmultirange[]
   */
  column2?: TimestampMultiRange[] | null
  /**
   * @kind smallint
   * 
   * @default nextval('newtable_column3_seq'::regclass)
   */
  column3?: Int2 | null
  /**
   * @kind smallint
   */
  column4?: Int2 | null
  /**
   * @kind character varying(45)
   */
  column5?: CharacterVarying<45> | null
  /**
   * @kind numeric
   */
  column6?: number | null
  /**
   * @kind numeric(7,3)
   */
  column7?: number | null
  /**
   * @kind numeric(6,0)
   */
  column8?: number | null
  /**
   * @kind numeric(2,-3)
   */
  column9?: number | null
}
export type {Newtable_InsertParameters}

const Newtable_InsertParameters_Data = {
  /**
   * @kind tstzmultirange[]
   */
  column1: PGTPParser(TimestampTZMultiRange, true).nullable().optional(),
  /**
   * @kind numeric(3,5)
   */
  column10: PGTPParser('unknown').nullable().optional(),
  /**
   * @kind numeric(2,-1)
   */
  column11: PGTPParser('unknown').nullable().optional(),
  /**
   * [extra1]:true
   * 
   * @kind numeric(2,-10)
   */
  column12: PGTPParser('unknown').nullable().optional(),
  /**
   * [extra2]:1
   * 
   * @kind numeric(2,1000)
   */
  column13: PGTPParser('unknown').nullable().optional(),
  /**
   * [extra3]:{key: "value"}
   * 
   * @kind numeric(2,-1000)
   */
  column14: PGTPParser('unknown').nullable().optional(),
  /**
   * @kind tsmultirange[]
   */
  column2: PGTPParser(TimestampMultiRange, true).nullable().optional(),
  /**
   * @kind smallint
   * 
   * @default nextval('newtable_column3_seq'::regclass)
   */
  column3: PGTPParser(Int2).nullable().optional(),
  /**
   * @kind smallint
   */
  column4: PGTPParser(Int2).nullable().optional(),
  /**
   * @kind character varying(45)
   */
  column5: PGTPParser(CharacterVarying.setN(45)).nullable().optional(),
  /**
   * @kind numeric
   */
  column6: PGTPParser('unknown').nullable().optional(),
  /**
   * @kind numeric(7,3)
   */
  column7: PGTPParser('unknown').nullable().optional(),
  /**
   * @kind numeric(6,0)
   */
  column8: PGTPParser('unknown').nullable().optional(),
  /**
   * @kind numeric(2,-3)
   */
  column9: PGTPParser('unknown').nullable().optional(),
};
export {Newtable_InsertParameters_Data}

const Newtable_PrimaryKey: undefined = undefined
export {Newtable_PrimaryKey}
