/**
 * !!! THIS FILE IS AUTOMATICALLY GENERATED, PLEASE DO NOT EDIT THIS FILE MANUALLY !!!
 *
 * Generated by: @PostgreSQL-Typed/CLI
 * Checksum: yAgDPnYXBKFW2wmiyQuPdO1ZdkipMVqcy1HebHWTxx0FfNJ0Riq8je5fvgfKaIiZd/0tj7yS8oTglxeVEIQzrA==
 */

/* eslint-disable */
// tslint:disable
/* deepscan-disable */

import {PGTPParser} from "@postgresql-typed/parsers";

import { Courses, Courses_Data } from './courses';
import { Grades, Grades_Data } from './grades';
import { Students, Students_Data } from './students';

interface StudentCourses {
  /**
   * @kind PrimaryKey
   * 
   * @kind text
   */
  course_id: Courses['course_id']
  /**
   * @kind text
   */
  grade: Grades['grade']
  /**
   * @kind PrimaryKey
   * 
   * @kind text
   */
  student_id: Students['student_id']
}
export type {StudentCourses}

const StudentCourses_Data = {
  /**
   * @kind PrimaryKey
   * 
   * @kind text
   */
  course_id: PGTPParser(Courses_Data['course_id']),
  /**
   * @kind text
   */
  grade: PGTPParser(Grades_Data['grade']),
  /**
   * @kind PrimaryKey
   * 
   * @kind text
   */
  student_id: PGTPParser(Students_Data['student_id']),
};
export {StudentCourses_Data}

interface StudentCourses_InsertParameters {
  /**
   * @kind PrimaryKey
   * 
   * @kind text
   */
  course_id: Courses['course_id']
  /**
   * @kind text
   */
  grade: Grades['grade']
  /**
   * @kind PrimaryKey
   * 
   * @kind text
   */
  student_id: Students['student_id']
}
export type {StudentCourses_InsertParameters}

const StudentCourses_InsertParameters_Data = {
  /**
   * @kind PrimaryKey
   * 
   * @kind text
   */
  course_id: PGTPParser(Courses_Data['course_id']),
  /**
   * @kind text
   */
  grade: PGTPParser(Grades_Data['grade']),
  /**
   * @kind PrimaryKey
   * 
   * @kind text
   */
  student_id: PGTPParser(Students_Data['student_id']),
};
export {StudentCourses_InsertParameters_Data}

const StudentCourses_PrimaryKey: "course_id" = "course_id"
export {StudentCourses_PrimaryKey}
