/**
 * !!! THIS FILE IS AUTOMATICALLY GENERATED, PLEASE DO NOT EDIT THIS FILE MANUALLY !!!
 *
 * Generated by: @PostgreSQL-Typed/CLI
 * Checksum: AIvzYIR9pQEIT4sC1rs7mJ1FEfimHl+DEyeeywrlgXkKgVp8qDIFkKu6VL85ujlsPWVBdMxi7ZU+tOPSbPM95A==
 */

/* eslint-disable */
// tslint:disable
/* deepscan-disable */

import {Text, PGTPParser} from "@postgresql-typed/parsers";

interface Students {
  /**
   * @kind text
   */
  student_first_name: Text
  /**
   * @kind PrimaryKey
   * 
   * @kind text
   */
  student_id: Text
  /**
   * @kind text
   */
  student_last_name: Text
}
export type {Students}

const Students_Data = {
  /**
   * @kind text
   */
  student_first_name: PGTPParser(Text),
  /**
   * @kind PrimaryKey
   * 
   * @kind text
   */
  student_id: PGTPParser(Text),
  /**
   * @kind text
   */
  student_last_name: PGTPParser(Text),
};
export {Students_Data}

interface Students_InsertParameters {
  /**
   * @kind text
   */
  student_first_name: Text
  /**
   * @kind PrimaryKey
   * 
   * @kind text
   */
  student_id: Text
  /**
   * @kind text
   */
  student_last_name: Text
}
export type {Students_InsertParameters}

const Students_InsertParameters_Data = {
  /**
   * @kind text
   */
  student_first_name: PGTPParser(Text),
  /**
   * @kind PrimaryKey
   * 
   * @kind text
   */
  student_id: PGTPParser(Text),
  /**
   * @kind text
   */
  student_last_name: PGTPParser(Text),
};
export {Students_InsertParameters_Data}

const Students_PrimaryKey: "student_id" = "student_id"
export {Students_PrimaryKey}
