/**
 * !!! THIS FILE IS AUTOMATICALLY GENERATED, PLEASE DO NOT EDIT THIS FILE MANUALLY !!!
 *
 * Generated by: @PostgreSQL-Typed/CLI
 * Checksum: BP0JTz87b/suYyLSC2nmNGvTqSe1+Tv6zcY6+7JWgHukt1SPWqw+SawTk7YRHO/xkOQLHIKGLg8EjBuXfWczNw==
 */

/* eslint-disable */
// tslint:disable
/* deepscan-disable */

import {Boolean, Int4, Timestamp, CharacterVarying, PGTPParser} from "@postgresql-typed/parsers";

interface Users {
  /**
   * @kind boolean
   * 
   * @default true
   */
  enabled: Boolean | null
  /**
   * @kind PrimaryKey
   * 
   * @kind integer
   * 
   * @default nextval('users_id_seq'::regclass)
   */
  id: Int4
  /**
   * @kind timestamp without time zone
   * 
   * @default now()
   */
  last_login: Timestamp
  /**
   * @kind character varying(25)
   */
  username: CharacterVarying<25>
}
export type {Users}

const Users_Data = {
  /**
   * @kind boolean
   * 
   * @default true
   */
  enabled: PGTPParser(Boolean).nullable(),
  /**
   * @kind PrimaryKey
   * 
   * @kind integer
   * 
   * @default nextval('users_id_seq'::regclass)
   */
  id: PGTPParser(Int4),
  /**
   * @kind timestamp without time zone
   * 
   * @default now()
   */
  last_login: PGTPParser(Timestamp),
  /**
   * @kind character varying(25)
   */
  username: PGTPParser(CharacterVarying.setN(25)),
};
export {Users_Data}

interface Users_InsertParameters {
  /**
   * @kind boolean
   * 
   * @default true
   */
  enabled?: Boolean | null
  /**
   * @kind PrimaryKey
   * 
   * @kind integer
   * 
   * @default nextval('users_id_seq'::regclass)
   */
  id?: Int4
  /**
   * @kind timestamp without time zone
   * 
   * @default now()
   */
  last_login?: Timestamp
  /**
   * @kind character varying(25)
   */
  username: CharacterVarying<25>
}
export type {Users_InsertParameters}

const Users_InsertParameters_Data = {
  /**
   * @kind boolean
   * 
   * @default true
   */
  enabled: PGTPParser(Boolean).nullable().optional(),
  /**
   * @kind PrimaryKey
   * 
   * @kind integer
   * 
   * @default nextval('users_id_seq'::regclass)
   */
  id: PGTPParser(Int4).optional(),
  /**
   * @kind timestamp without time zone
   * 
   * @default now()
   */
  last_login: PGTPParser(Timestamp).optional(),
  /**
   * @kind character varying(25)
   */
  username: PGTPParser(CharacterVarying.setN(25)),
};
export {Users_InsertParameters_Data}

const Users_PrimaryKey: "id" = "id"
export {Users_PrimaryKey}
