import debug from "debug";

const {
	description,
	version,
}: {
	description: string;
	version: string;
	// eslint-disable-next-line @typescript-eslint/no-var-requires
} = require("../../package.json");

export const NAME = "PostgreSQL-Types-Generator";
export const DESCRIPTION = description;
export const VERSION = version;
export const LOGGER = debug(NAME);
export const MODULE_NAME = "pgtg";
export const GENERATED_STATEMENT = `Generated by: ${NAME}`;
export const GLOBAL_DEBUG_GLOB = `${NAME}:*`;
