import { DataType } from "postgresql-data-types";

const TypeScriptMapping: {
	[key in DataType]: string | [string, string[]];
} = {
	[DataType._abstime]: "unknown[]",
	[DataType._aclitem]: "unknown[]",
	[DataType._bit]: "string[]",
	[DataType._bool]: "boolean[]",
	[DataType._box]: ["Box[]", ['import type { Box } from "postgresql-typed";']],
	[DataType._bpchar]: "string[]",
	[DataType._bytea]: "Buffer[]",
	[DataType._char]: "string[]",
	[DataType._cid]: "string[]",
	[DataType._cidr]: ["IPAddress[]", ['import type { IPAddress } from "postgresql-typed";']],
	[DataType._circle]: ["Circle[]", ['import type { Circle } from "postgresql-typed";']],
	[DataType._cstring]: "string[]",
	[DataType._date]: ["Date[]", ['import type { Date } from "postgresql-typed";']],
	[DataType._datemultirange]: ["DateMultiRange[]", ['import type { DateMultiRange } from "postgresql-typed";']],
	[DataType._daterange]: ["DateRange[]", ['import type { DateRange } from "postgresql-typed";']],
	[DataType._float4]: "number[]",
	[DataType._float8]: "number[]",
	[DataType._gtsvector]: "unknown[]",
	[DataType._inet]: ["IPAddress[]", ['import type { IPAddress } from "postgresql-typed";']],
	[DataType._int2]: "number[]",
	[DataType._int2vector]: "unknown[]",
	[DataType._int4]: "number[]",
	[DataType._int4multirange]: "unknown[]",
	[DataType._int4range]: "unknown[]",
	[DataType._int8]: "unknown[]",
	[DataType._int8multirange]: "unknown[]",
	[DataType._int8range]: "unknown[]",
	[DataType._interval]: ["Interval[]", ['import type { Interval } from "postgresql-typed";']],
	[DataType._json]: ["Json[]", ['import type { Json } from "postgresql-types-generator";']],
	[DataType._jsonb]: ["Json[]", ['import type { Json } from "postgresql-types-generator";']],
	[DataType._jsonpath]: "unknown[]",
	[DataType._line]: ["Line[]", ['import type { Line } from "postgresql-typed";']],
	[DataType._lseg]: ["LineSegment[]", ['import type { LineSegment } from "postgresql-typed";']],
	[DataType._macaddr]: ["MACAddress[]", ['import type { MACAddress } from "postgresql-typed";']],
	[DataType._macaddr8]: ["MACAddress8[]", ['import type { MACAddress8 } from "postgresql-typed";']],
	[DataType._money]: "string[]",
	[DataType._name]: "string[]",
	[DataType._numeric]: "number[]",
	[DataType._nummultirange]: "unknown[]",
	[DataType._numrange]: "unknown[]",
	[DataType._oid]: "number[]",
	[DataType._oidvector]: "unknown[]",
	[DataType._path]: ["Path[]", ['import type { Path } from "postgresql-typed";']],
	[DataType._pg_lsn]: "unknown[]",
	[DataType._pg_snapshot]: "unknown[]",
	[DataType._point]: ["Point[]", ['import type { Point } from "postgresql-typed";']],
	[DataType._polygon]: ["Polygon[]", ['import type { Polygon } from "postgresql-typed";']],
	[DataType._record]: "unknown[]",
	[DataType._refcursor]: "unknown[]",
	[DataType._regclass]: "unknown[]",
	[DataType._regcollation]: "unknown[]",
	[DataType._regconfig]: "unknown[]",
	[DataType._regdictionary]: "unknown[]",
	[DataType._regnamespace]: "unknown[]",
	[DataType._regoper]: "unknown[]",
	[DataType._regoperator]: "unknown[]",
	[DataType._regproc]: "unknown[]",
	[DataType._regprocedure]: "unknown[]",
	[DataType._regrole]: "unknown[]",
	[DataType._regtype]: "unknown[]",
	[DataType._reltime]: "unknown[]",
	[DataType._text]: "string[]",
	[DataType._tid]: "unknown[]",
	[DataType._time]: ["Time[]", ['import type { Time } from "postgresql-typed";']],
	[DataType._timestamp]: ["Timestamp[]", ['import type { Timestamp } from "postgresql-typed";']],
	[DataType._timestamptz]: ["TimestampTZ[]", ['import type { TimestampTZ } from "postgresql-typed";']],
	[DataType._timetz]: ["TimeTZ[]", ['import type { TimeTZ } from "postgresql-typed";']],
	[DataType._tinterval]: "unknown[]",
	[DataType._tsquery]: "unknown[]",
	[DataType._tsmultirange]: ["TimestampMultiRange[]", ['import type { TimestampMultiRange } from "postgresql-typed";']],
	[DataType._tsrange]: ["TimestampRange[]", ['import type { TimestampRange } from "postgresql-typed";']],
	[DataType._tstzmultirange]: ["TimestampTZMultiRange[]", ['import type { TimestampTZMultiRange } from "postgresql-typed";']],
	[DataType._tstzrange]: ["TimestampTZRange[]", ['import type { TimestampTZRange } from "postgresql-typed";']],
	[DataType._tsvector]: "unknown[]",
	[DataType._txid_snapshot]: "unknown[]",
	[DataType._uuid]: ["UUID[]", ['import type { UUID } from "postgresql-typed";']],
	[DataType._varbit]: "string[]",
	[DataType._varchar]: "string[]",
	[DataType._xid]: "unknown[]",
	[DataType._xid8]: "unknown[]",
	[DataType._xml]: "unknown[]",
	[DataType.abstime]: "unknown",
	[DataType.aclitem]: "unknown",
	[DataType.any]: "unknown",
	[DataType.anyarray]: "unknown",
	[DataType.anycompatible]: "unknown",
	[DataType.anycompatiblearray]: "unknown",
	[DataType.anycompatiblemultirange]: "unknown",
	[DataType.anycompatiblenonarray]: "unknown",
	[DataType.anycompatiblerange]: "unknown",
	[DataType.anyelement]: "unknown",
	[DataType.anyenum]: "unknown",
	[DataType.anymultirange]: "unknown",
	[DataType.anynonarray]: "unknown",
	[DataType.anyrange]: "unknown",
	[DataType.bit]: "unknown",
	[DataType.bool]: "boolean",
	[DataType.box]: ["Box", ['import type { Box } from "postgresql-typed";']],
	[DataType.bpchar]: "string",
	[DataType.bytea]: "Buffer",
	[DataType.cardinal_number]: "unknown",
	[DataType.char]: "string",
	[DataType.character_data]: "unknown",
	[DataType.cid]: "string",
	[DataType.cidr]: ["CIDR", ['import type { CIDR } from "postgresql-typed";']],
	[DataType.circle]: ["Circle", ['import type { Circle } from "postgresql-typed";']],
	[DataType.cstring]: "string",
	[DataType.date]: ["Date", ['import type { Date } from "postgresql-typed";']],
	[DataType.datemultirange]: ["DateMultiRange", ['import type { DateMultiRange } from "postgresql-typed";']],
	[DataType.daterange]: ["DateRange", ['import type { DateRange } from "postgresql-typed";']],
	[DataType.event_trigger]: "unknown",
	[DataType.fdw_handler]: "unknown",
	[DataType.float4]: "number",
	[DataType.float8]: "number",
	[DataType.gtsvector]: "unknown",
	[DataType.index_am_handler]: "unknown",
	[DataType.inet]: ["IPAddress", ['import type { IPAddress } from "postgresql-typed";']],
	[DataType.int2]: "number",
	[DataType.int2vector]: "unknown",
	[DataType.int4]: "number",
	[DataType.int4multirange]: "unknown",
	[DataType.int4range]: "unknown",
	[DataType.int8]: "unknown",
	[DataType.int8multirange]: "unknown",
	[DataType.int8range]: "unknown",
	[DataType.internal]: "unknown",
	[DataType.interval]: ["Interval", ['import type { Interval } from "postgresql-typed";']],
	[DataType.json]: ["Json", ['import type { Json } from "postgresql-types-generator/lib/util/zJson";']],
	[DataType.jsonb]: ["Json", ['import type { Json } from "postgresql-types-generator/lib/util/zJson";']],
	[DataType.jsonpath]: "unknown",
	[DataType.language_handler]: "unknown",
	[DataType.line]: ["Line", ['import type { Line } from "postgresql-typed";']],
	[DataType.lseg]: ["LineSegment", ['import type { LineSegment } from "postgresql-typed";']],
	[DataType.macaddr]: ["MACAddress", ['import type { MACAddress } from "postgresql-typed";']],
	[DataType.macaddr8]: ["MACAddress8", ['import type { MACAddress8 } from "postgresql-typed";']],
	[DataType.money]: "string",
	[DataType.name]: "string",
	[DataType.numeric]: "number",
	[DataType.nummultirange]: "unknown",
	[DataType.numrange]: "unknown",
	[DataType.oid]: "number",
	[DataType.oidvector]: "unknown",
	[DataType.opaque]: "unknown",
	[DataType.path]: ["Path", ['import type { Path } from "postgresql-typed";']],
	[DataType.pg_brin_bloom_summary]: "unknown",
	[DataType.pg_brin_minmax_multi_summary]: "unknown",
	[DataType.pg_ddl_command]: "unknown",
	[DataType.pg_dependencies]: "unknown",
	[DataType.pg_lsn]: "unknown",
	[DataType.pg_mcv_list]: "unknown",
	[DataType.pg_ndistinct]: "unknown",
	[DataType.pg_node_tree]: "unknown",
	[DataType.pg_snapshot]: "unknown",
	[DataType.point]: ["Point", ['import type { Point } from "postgresql-typed";']],
	[DataType.polygon]: ["Polygon", ['import type { Polygon } from "postgresql-typed";']],
	[DataType.record]: "unknown",
	[DataType.refcursor]: "unknown",
	[DataType.regcollation]: "unknown",
	[DataType.regclass]: "unknown",
	[DataType.regconfig]: "unknown",
	[DataType.regdictionary]: "unknown",
	[DataType.regnamespace]: "unknown",
	[DataType.regoper]: "unknown",
	[DataType.regoperator]: "unknown",
	[DataType.regproc]: "unknown",
	[DataType.regprocedure]: "unknown",
	[DataType.regrole]: "unknown",
	[DataType.regtype]: "unknown",
	[DataType.reltime]: "unknown",
	[DataType.smgr]: "unknown",
	[DataType.table_am_handler]: "unknown",
	[DataType.text]: "string",
	[DataType.tid]: "unknown",
	[DataType.time]: ["Time", ['import type { Time } from "postgresql-typed";']],
	[DataType.timestamp]: ["Timestamp", ['import type { Timestamp } from "postgresql-typed";']],
	[DataType.timestamptz]: ["TimestampTZ", ['import type { TimestampTZ } from "postgresql-typed";']],
	[DataType.timetz]: ["TimeTZ", ['import type { TimeTZ } from "postgresql-typed";']],
	[DataType.tinterval]: "unknown",
	[DataType.trigger]: "unknown",
	[DataType.tsm_handler]: "unknown",
	[DataType.tsmultirange]: "unknown",
	[DataType.tsquery]: "unknown",
	[DataType.tsrange]: ["TimestampRange", ['import type { TimestampRange } from "postgresql-typed";']],
	[DataType.tstzmultirange]: "unknown",
	[DataType.tstzrange]: ["TimestampTZRange", ['import type { TimestampTZRange } from "postgresql-typed";']],
	[DataType.tsvector]: "unknown",
	[DataType.txid_snapshot]: "unknown",
	[DataType.unknown]: "unknown",
	[DataType.uuid]: ["UUID", ['import type { UUID } from "postgresql-typed";']],
	[DataType.varbit]: "string",
	[DataType.varchar]: "string",
	[DataType.void]: "unknown",
	[DataType.xid]: "unknown",
	[DataType.xid8]: "unknown",
	[DataType.xml]: "unknown",
};

export const DefaultTypeScriptMapping = new Map<DataType, string | [string, string[]]>(
	Object.entries(TypeScriptMapping) as unknown as Readonly<[DataType, string | [string, string[]]][]>
);
