/**
 * !!! THIS FILE IS AUTOMATICALLY GENERATED, PLEASE DO NOT EDIT THIS FILE MANUALLY !!!
 *
 * Generated by: @PostgreSQL-Typed/CLI
 * Checksum: nCxBn0li46LjP6zKFANGi9/qinKKhZEX4iO/4n+Zm7SqffwuohqixesdpwsQNyFA+nqRkhKQ5hhsp0qVAHquFw==
 */

/* eslint-disable */
// tslint:disable
/* deepscan-disable */

import { Public, Public_Data } from './postgres/public';

interface Postgres {
  name: "postgres";
  schemas: {
    public: Public
  }
}
export type {Postgres}

const Postgres_Data = {
  name: "postgres" as const,
  schemas: [
    Public_Data
  ]
}
export {Postgres_Data}
