name: Prepare Environment
description: Prepare the environment for the build
runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2

    - name: Install Node
      uses: actions/setup-node@v3
      with:
        cache: pnpm

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile