name: Prepare Environment
description: Prepare the environment for the build
inputs:
  node-version:
    description: The Node.js version to use
    required: false
    default: '16'
runs:
  using: composite
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        cache: pnpm
        node-version: ${{ inputs.node-version }}

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile