/**
 * !!! THIS FILE IS AUTOMATICALLY GENERATED, PLEASE DO NOT EDIT THIS FILE MANUALLY !!!
 *
 * Generated by: @PostgreSQL-Typed/CLI
 * Checksum: kLAvMgHIah4DZwdpG+voWG/l/V3sEgrx3f9sZ+bA6LQD9yItr3AQdskqzgc1NOw06E0hh3VR3sgG1hmTnbcRjw==
 */

/* eslint-disable */
// tslint:disable
/* deepscan-disable */

import { Postgres, Postgres_Data } from './databases/postgres';

type Databases = {
  "postgres": Postgres
}
export type {Databases}

const Databases_Data = {
  "postgres": Postgres_Data
}
export {Databases_Data}
