/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CodeMirror: typeof import('./components/CodeMirror.vue')['default']
    Dashboard: typeof import('./components/Dashboard.vue')['default']
    Dropdown: typeof import('./components/Dropdown.vue')['default']
    Graph: typeof import('./components/View/Graph.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconButton: typeof import('./components/IconButton.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    Menu: typeof import('./components/Menu.vue')['default']
    MenuGroup: typeof import('./components/MenuGroup.vue')['default']
    MenuLink: typeof import('./components/MenuLink.vue')['default']
    Navigation: typeof import('./components/Navigation.vue')['default']
    NoData: typeof import('./components/NoData.vue')['default']
    Select: typeof import('./components/Select.vue')['default']
    TableDetails: typeof import('./components/TableDetails.vue')['default']
    TableItem: typeof import('./components/TableItem.vue')['default']
    TableList: typeof import('./components/TableList.vue')['default']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    ViewDiagram: typeof import('./components/View/ViewDiagram.vue')['default']
    ViewEditor: typeof import('./components/View/ViewEditor.vue')['default']
    ViewGraph: typeof import('./components/View/ViewGraph.vue')['default']
    ViewTable: typeof import('./components/View/ViewTable.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
}
