/**
 * !!! THIS FILE IS AUTOMATICALLY GENERATED, PLEASE DO NOT EDIT THIS FILE MANUALLY !!!
 *
 * Generated by: @PostgreSQL-Typed/CLI
 * Checksum: fUCjxR7YmTMPY6fxX70H+JnL93OO+wQ43RAuRlhW/3CqNsfAFBa6FfQJb67kfZpoDIfcVLyUoT0b7qMm4h/fhw==
 */

/* eslint-disable */
// tslint:disable
/* deepscan-disable */

import { Addresses, Addresses_Data, Addresses_InsertParameters, Addresses_InsertParameters_Data, Addresses_PrimaryKey } from './public/addresses';
import { Aircraft, Aircraft_Data, Aircraft_InsertParameters, Aircraft_InsertParameters_Data, Aircraft_PrimaryKey } from './public/aircraft';
import { Article, Article_Data, Article_InsertParameters, Article_InsertParameters_Data, Article_PrimaryKey } from './public/article';
import { ArticleTag, ArticleTag_Data, ArticleTag_InsertParameters, ArticleTag_InsertParameters_Data, ArticleTag_PrimaryKey } from './public/article_tag';
import { Courses, Courses_Data, Courses_InsertParameters, Courses_InsertParameters_Data, Courses_PrimaryKey } from './public/courses';
import { Grades, Grades_Data, Grades_InsertParameters, Grades_InsertParameters_Data, Grades_PrimaryKey } from './public/grades';
import { Newtable, Newtable_Data, Newtable_InsertParameters, Newtable_InsertParameters_Data, Newtable_PrimaryKey } from './public/newtable';
import { StudentCourses, StudentCourses_Data, StudentCourses_InsertParameters, StudentCourses_InsertParameters_Data, StudentCourses_PrimaryKey } from './public/student_courses';
import { Students, Students_Data, Students_InsertParameters, Students_InsertParameters_Data, Students_PrimaryKey } from './public/students';
import { Tag, Tag_Data, Tag_InsertParameters, Tag_InsertParameters_Data, Tag_PrimaryKey } from './public/tag';
import { Users, Users_Data, Users_InsertParameters, Users_InsertParameters_Data, Users_PrimaryKey } from './public/users';

interface Public {
  name: "public";
  tables: {
    addresses: {
      name: "addresses";
      primary_key: typeof Addresses_PrimaryKey;
      columns: Addresses;
      insert_parameters: Addresses_InsertParameters;
    };
    aircraft: {
      name: "aircraft";
      primary_key: typeof Aircraft_PrimaryKey;
      columns: Aircraft;
      insert_parameters: Aircraft_InsertParameters;
    };
    article: {
      name: "article";
      primary_key: typeof Article_PrimaryKey;
      columns: Article;
      insert_parameters: Article_InsertParameters;
    };
    article_tag: {
      name: "article_tag";
      primary_key: typeof ArticleTag_PrimaryKey;
      columns: ArticleTag;
      insert_parameters: ArticleTag_InsertParameters;
    };
    courses: {
      name: "courses";
      primary_key: typeof Courses_PrimaryKey;
      columns: Courses;
      insert_parameters: Courses_InsertParameters;
    };
    grades: {
      name: "grades";
      primary_key: typeof Grades_PrimaryKey;
      columns: Grades;
      insert_parameters: Grades_InsertParameters;
    };
    newtable: {
      name: "newtable";
      primary_key: typeof Newtable_PrimaryKey;
      columns: Newtable;
      insert_parameters: Newtable_InsertParameters;
    };
    student_courses: {
      name: "student_courses";
      primary_key: typeof StudentCourses_PrimaryKey;
      columns: StudentCourses;
      insert_parameters: StudentCourses_InsertParameters;
    };
    students: {
      name: "students";
      primary_key: typeof Students_PrimaryKey;
      columns: Students;
      insert_parameters: Students_InsertParameters;
    };
    tag: {
      name: "tag";
      primary_key: typeof Tag_PrimaryKey;
      columns: Tag;
      insert_parameters: Tag_InsertParameters;
    };
    users: {
      name: "users";
      primary_key: typeof Users_PrimaryKey;
      columns: Users;
      insert_parameters: Users_InsertParameters;
    };
  };
};
export type {Public}

const Public_Data = {
  name: "public" as const,
  tables: [
    {
      name: "addresses" as const,
      primary_key: Addresses_PrimaryKey,
      columns: Addresses_Data,
      insert_parameters: Addresses_InsertParameters_Data
    },
    {
      name: "aircraft" as const,
      primary_key: Aircraft_PrimaryKey,
      columns: Aircraft_Data,
      insert_parameters: Aircraft_InsertParameters_Data
    },
    {
      name: "article" as const,
      primary_key: Article_PrimaryKey,
      columns: Article_Data,
      insert_parameters: Article_InsertParameters_Data
    },
    {
      name: "article_tag" as const,
      primary_key: ArticleTag_PrimaryKey,
      columns: ArticleTag_Data,
      insert_parameters: ArticleTag_InsertParameters_Data
    },
    {
      name: "courses" as const,
      primary_key: Courses_PrimaryKey,
      columns: Courses_Data,
      insert_parameters: Courses_InsertParameters_Data
    },
    {
      name: "grades" as const,
      primary_key: Grades_PrimaryKey,
      columns: Grades_Data,
      insert_parameters: Grades_InsertParameters_Data
    },
    {
      name: "newtable" as const,
      primary_key: Newtable_PrimaryKey,
      columns: Newtable_Data,
      insert_parameters: Newtable_InsertParameters_Data
    },
    {
      name: "student_courses" as const,
      primary_key: StudentCourses_PrimaryKey,
      columns: StudentCourses_Data,
      insert_parameters: StudentCourses_InsertParameters_Data
    },
    {
      name: "students" as const,
      primary_key: Students_PrimaryKey,
      columns: Students_Data,
      insert_parameters: Students_InsertParameters_Data
    },
    {
      name: "tag" as const,
      primary_key: Tag_PrimaryKey,
      columns: Tag_Data,
      insert_parameters: Tag_InsertParameters_Data
    },
    {
      name: "users" as const,
      primary_key: Users_PrimaryKey,
      columns: Users_Data,
      insert_parameters: Users_InsertParameters_Data
    }
  ]
};
export {Public_Data}
