import { readFileSync } from "node:fs";

import debug from "debug";

const { description, version } = JSON.parse(readFileSync(new URL("../../package.json", import.meta.url)).toString());

export const NAME = "@PostgreSQL-Typed/CLI";
export const UI_PACKAGE = "@postgresql-typed/ui";
export const DESCRIPTION = description;
export const VERSION = version;
const logger = debug(NAME);
//* This is a workaround for the UI package, wherein the debug package gets bundled into the UI package, which causes the debug package to not work properly.
export const LOGGER = "extends" in logger && typeof logger.extends === "function" ? logger : undefined;
export const MODULE_NAME = "pgt";
export const GENERATED_STATEMENT = `Generated by: ${NAME}`;
export const GLOBAL_DEBUG_GLOB = `${NAME}:*`;
