import { readFileSync } from "node:fs";

import debug from "debug";

const { description, version } = JSON.parse(readFileSync(new URL("../../package.json", import.meta.url)).toString());

export const NAME = "@PostgreSQL-Typed/CLI";
export const DESCRIPTION = description;
export const VERSION = version;
export const LOGGER = debug(NAME);
export const MODULE_NAME = "pgt";
export const GENERATED_STATEMENT = `Generated by: ${NAME}`;
export const GLOBAL_DEBUG_GLOB = `${NAME}:*`;
