import { OID } from "@postgresql-typed/oids";

const TypeScriptMapping: {
	[key in OID]: string | [string, string[]];
} = {
	[OID._abstime]: "unknown[]",
	[OID._aclitem]: "unknown[]",
	[OID._bit]: "string[]",
	[OID._bool]: "boolean[]",
	[OID._box]: ["Box[]", ['import type { Box } from "postgresql-typed";']],
	[OID._bpchar]: "string[]",
	[OID._bytea]: "Buffer[]",
	[OID._char]: "string[]",
	[OID._cid]: "string[]",
	[OID._cidr]: ["IPAddress[]", ['import type { IPAddress } from "postgresql-typed";']],
	[OID._circle]: ["Circle[]", ['import type { Circle } from "postgresql-typed";']],
	[OID._cstring]: "string[]",
	[OID._date]: ["Date[]", ['import type { Date } from "postgresql-typed";']],
	[OID._datemultirange]: ["DateMultiRange[]", ['import type { DateMultiRange } from "postgresql-typed";']],
	[OID._daterange]: ["DateRange[]", ['import type { DateRange } from "postgresql-typed";']],
	[OID._float4]: "number[]",
	[OID._float8]: "number[]",
	[OID._gtsvector]: "unknown[]",
	[OID._inet]: ["IPAddress[]", ['import type { IPAddress } from "postgresql-typed";']],
	[OID._int2]: "number[]",
	[OID._int2vector]: "unknown[]",
	[OID._int4]: "number[]",
	[OID._int4multirange]: "unknown[]",
	[OID._int4range]: "unknown[]",
	[OID._int8]: "unknown[]",
	[OID._int8multirange]: "unknown[]",
	[OID._int8range]: "unknown[]",
	[OID._interval]: ["Interval[]", ['import type { Interval } from "postgresql-typed";']],
	[OID._json]: ["Json[]", ['import type { Json } from "postgresql-types-generator";']],
	[OID._jsonb]: ["Json[]", ['import type { Json } from "postgresql-types-generator";']],
	[OID._jsonpath]: "unknown[]",
	[OID._line]: ["Line[]", ['import type { Line } from "postgresql-typed";']],
	[OID._lseg]: ["LineSegment[]", ['import type { LineSegment } from "postgresql-typed";']],
	[OID._macaddr]: ["MACAddress[]", ['import type { MACAddress } from "postgresql-typed";']],
	[OID._macaddr8]: ["MACAddress8[]", ['import type { MACAddress8 } from "postgresql-typed";']],
	[OID._money]: "string[]",
	[OID._name]: "string[]",
	[OID._numeric]: "number[]",
	[OID._nummultirange]: "unknown[]",
	[OID._numrange]: "unknown[]",
	[OID._oid]: "number[]",
	[OID._oidvector]: "unknown[]",
	[OID._path]: ["Path[]", ['import type { Path } from "postgresql-typed";']],
	[OID._pg_lsn]: "unknown[]",
	[OID._pg_snapshot]: "unknown[]",
	[OID._point]: ["Point[]", ['import type { Point } from "postgresql-typed";']],
	[OID._polygon]: ["Polygon[]", ['import type { Polygon } from "postgresql-typed";']],
	[OID._record]: "unknown[]",
	[OID._refcursor]: "unknown[]",
	[OID._regclass]: "unknown[]",
	[OID._regcollation]: "unknown[]",
	[OID._regconfig]: "unknown[]",
	[OID._regdictionary]: "unknown[]",
	[OID._regnamespace]: "unknown[]",
	[OID._regoper]: "unknown[]",
	[OID._regoperator]: "unknown[]",
	[OID._regproc]: "unknown[]",
	[OID._regprocedure]: "unknown[]",
	[OID._regrole]: "unknown[]",
	[OID._regtype]: "unknown[]",
	[OID._reltime]: "unknown[]",
	[OID._text]: "string[]",
	[OID._tid]: "unknown[]",
	[OID._time]: ["Time[]", ['import type { Time } from "postgresql-typed";']],
	[OID._timestamp]: ["Timestamp[]", ['import type { Timestamp } from "postgresql-typed";']],
	[OID._timestamptz]: ["TimestampTZ[]", ['import type { TimestampTZ } from "postgresql-typed";']],
	[OID._timetz]: ["TimeTZ[]", ['import type { TimeTZ } from "postgresql-typed";']],
	[OID._tinterval]: "unknown[]",
	[OID._tsquery]: "unknown[]",
	[OID._tsmultirange]: ["TimestampMultiRange[]", ['import type { TimestampMultiRange } from "postgresql-typed";']],
	[OID._tsrange]: ["TimestampRange[]", ['import type { TimestampRange } from "postgresql-typed";']],
	[OID._tstzmultirange]: ["TimestampTZMultiRange[]", ['import type { TimestampTZMultiRange } from "postgresql-typed";']],
	[OID._tstzrange]: ["TimestampTZRange[]", ['import type { TimestampTZRange } from "postgresql-typed";']],
	[OID._tsvector]: "unknown[]",
	[OID._txid_snapshot]: "unknown[]",
	[OID._uuid]: ["UUID[]", ['import type { UUID } from "postgresql-typed";']],
	[OID._varbit]: "string[]",
	[OID._varchar]: "string[]",
	[OID._xid]: "unknown[]",
	[OID._xid8]: "unknown[]",
	[OID._xml]: "unknown[]",
	[OID.abstime]: "unknown",
	[OID.aclitem]: "unknown",
	[OID.any]: "unknown",
	[OID.anyarray]: "unknown",
	[OID.anycompatible]: "unknown",
	[OID.anycompatiblearray]: "unknown",
	[OID.anycompatiblemultirange]: "unknown",
	[OID.anycompatiblenonarray]: "unknown",
	[OID.anycompatiblerange]: "unknown",
	[OID.anyelement]: "unknown",
	[OID.anyenum]: "unknown",
	[OID.anymultirange]: "unknown",
	[OID.anynonarray]: "unknown",
	[OID.anyrange]: "unknown",
	[OID.bit]: "unknown",
	[OID.bool]: "boolean",
	[OID.box]: ["Box", ['import type { Box } from "postgresql-typed";']],
	[OID.bpchar]: "string",
	[OID.bytea]: "Buffer",
	[OID.cardinal_number]: "unknown",
	[OID.char]: "string",
	[OID.character_data]: "unknown",
	[OID.cid]: "string",
	[OID.cidr]: ["CIDR", ['import type { CIDR } from "postgresql-typed";']],
	[OID.circle]: ["Circle", ['import type { Circle } from "postgresql-typed";']],
	[OID.cstring]: "string",
	[OID.date]: ["Date", ['import type { Date } from "postgresql-typed";']],
	[OID.datemultirange]: ["DateMultiRange", ['import type { DateMultiRange } from "postgresql-typed";']],
	[OID.daterange]: ["DateRange", ['import type { DateRange } from "postgresql-typed";']],
	[OID.event_trigger]: "unknown",
	[OID.fdw_handler]: "unknown",
	[OID.float4]: "number",
	[OID.float8]: "number",
	[OID.gtsvector]: "unknown",
	[OID.index_am_handler]: "unknown",
	[OID.inet]: ["IPAddress", ['import type { IPAddress } from "postgresql-typed";']],
	[OID.int2]: "number",
	[OID.int2vector]: "unknown",
	[OID.int4]: "number",
	[OID.int4multirange]: "unknown",
	[OID.int4range]: "unknown",
	[OID.int8]: "unknown",
	[OID.int8multirange]: "unknown",
	[OID.int8range]: "unknown",
	[OID.internal]: "unknown",
	[OID.interval]: ["Interval", ['import type { Interval } from "postgresql-typed";']],
	[OID.json]: ["Json", ['import type { Json } from "postgresql-types-generator/lib/util/zJson";']],
	[OID.jsonb]: ["Json", ['import type { Json } from "postgresql-types-generator/lib/util/zJson";']],
	[OID.jsonpath]: "unknown",
	[OID.language_handler]: "unknown",
	[OID.line]: ["Line", ['import type { Line } from "postgresql-typed";']],
	[OID.lseg]: ["LineSegment", ['import type { LineSegment } from "postgresql-typed";']],
	[OID.macaddr]: ["MACAddress", ['import type { MACAddress } from "postgresql-typed";']],
	[OID.macaddr8]: ["MACAddress8", ['import type { MACAddress8 } from "postgresql-typed";']],
	[OID.money]: "string",
	[OID.name]: "string",
	[OID.numeric]: "number",
	[OID.nummultirange]: "unknown",
	[OID.numrange]: "unknown",
	[OID.oid]: "number",
	[OID.oidvector]: "unknown",
	[OID.opaque]: "unknown",
	[OID.path]: ["Path", ['import type { Path } from "postgresql-typed";']],
	[OID.pg_brin_bloom_summary]: "unknown",
	[OID.pg_brin_minmax_multi_summary]: "unknown",
	[OID.pg_ddl_command]: "unknown",
	[OID.pg_dependencies]: "unknown",
	[OID.pg_lsn]: "unknown",
	[OID.pg_mcv_list]: "unknown",
	[OID.pg_ndistinct]: "unknown",
	[OID.pg_node_tree]: "unknown",
	[OID.pg_snapshot]: "unknown",
	[OID.point]: ["Point", ['import type { Point } from "postgresql-typed";']],
	[OID.polygon]: ["Polygon", ['import type { Polygon } from "postgresql-typed";']],
	[OID.record]: "unknown",
	[OID.refcursor]: "unknown",
	[OID.regcollation]: "unknown",
	[OID.regclass]: "unknown",
	[OID.regconfig]: "unknown",
	[OID.regdictionary]: "unknown",
	[OID.regnamespace]: "unknown",
	[OID.regoper]: "unknown",
	[OID.regoperator]: "unknown",
	[OID.regproc]: "unknown",
	[OID.regprocedure]: "unknown",
	[OID.regrole]: "unknown",
	[OID.regtype]: "unknown",
	[OID.reltime]: "unknown",
	[OID.smgr]: "unknown",
	[OID.table_am_handler]: "unknown",
	[OID.text]: "string",
	[OID.tid]: "unknown",
	[OID.time]: ["Time", ['import type { Time } from "postgresql-typed";']],
	[OID.timestamp]: ["Timestamp", ['import type { Timestamp } from "postgresql-typed";']],
	[OID.timestamptz]: ["TimestampTZ", ['import type { TimestampTZ } from "postgresql-typed";']],
	[OID.timetz]: ["TimeTZ", ['import type { TimeTZ } from "postgresql-typed";']],
	[OID.tinterval]: "unknown",
	[OID.trigger]: "unknown",
	[OID.tsm_handler]: "unknown",
	[OID.tsmultirange]: "unknown",
	[OID.tsquery]: "unknown",
	[OID.tsrange]: ["TimestampRange", ['import type { TimestampRange } from "postgresql-typed";']],
	[OID.tstzmultirange]: "unknown",
	[OID.tstzrange]: ["TimestampTZRange", ['import type { TimestampTZRange } from "postgresql-typed";']],
	[OID.tsvector]: "unknown",
	[OID.txid_snapshot]: "unknown",
	[OID.unknown]: "unknown",
	[OID.uuid]: ["UUID", ['import type { UUID } from "postgresql-typed";']],
	[OID.varbit]: "string",
	[OID.varchar]: "string",
	[OID.void]: "unknown",
	[OID.xid]: "unknown",
	[OID.xid8]: "unknown",
	[OID.xml]: "unknown",
};

export const DefaultTypeScriptMapping = new Map<OID, string | [string, string[]]>(
	Object.entries(TypeScriptMapping) as unknown as Readonly<[OID, string | [string, string[]]][]>
);
